# fly.toml app configuration file generated for moneygun on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moneygun"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  RAILS_ENV = "production"
  BUNDLE_WITHOUT = "development:test"
  SOLID_QUEUE_IN_PUMA = "true"
  JEMALLOC_ENABLED = "true"
  MALLOC_ARENA_MAX = "2"
  SENSIBLE_DEFAULTS = "enabled"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory_mb = 1024
  cpu_kind = "shared"
  cpus = 1

