# Rails.application.config_for(:settings).dig(:site, :name)
shared:
  site:
    name: Moneygun
    email: hello@superails.com
    address: Warsaw, Poland, 02-691
  pro_features:
    - ☑️ Access the paywalled page
  plans:
    - id: price_1R68c1LRcgxgTmfQijgGMDfT
      unit_amount: 9900
      currency: USD
      interval: month
    - id: price_1R68c1LRcgxgTmfQijgGMDfT
      unit_amount: 99900
      currency: USD
      interval: year
production:
  plans:
    - id: price_1R68c1LRcgxgTmfQijgGMDfT
      unit_amount: 1900
      currency: USD
      interval: month
    - id: price_1R68c1LRcgxgTmfQijgGMDfT
      unit_amount: 19000
      currency: USD
      interval: year
