# Rails.application.config_for(:settings).dig(:site, :name)
shared:
  site:
    name: Moneygun
    email: hello@superails.com
    address: Warsaw, Poland, 02-691
  pro_features:
    - ☑️ Access the paywalled page
    - ☑️ Create more than 1 project
  plans:
    - id: price_1RDRzvLRcgxgTmfQZVdAF93B
      unit_amount: 9900
      currency: USD
      interval: month
    - id: price_1RDRzwLRcgxgTmfQZigxB6ZM
      unit_amount: 99900
      currency: USD
      interval: year
production:
  plans:
    - id: price_1RDRzvLRcgxgTmfQZVdAF93B
      unit_amount: 9900
      currency: USD
      interval: month
    - id: price_1RDRzwLRcgxgTmfQZigxB6ZM
      unit_amount: 99900
      currency: USD
      interval: year
