# Rails.application.config_for(:settings).dig(:site, :name)
shared:
  site:
    name: Moneygun
    email: hello@superails.com
    address: Warsaw, Poland, 02-691
  pro_features:
    - âœ… Access the paywalled page
  plan_price_ids:
    - price_1SYWIEGHcaLYld8I3aEP3Qpp
    - price_1SYWIdGHcaLYld8IFWrZkAho
# production:
#   plan_price_ids:
#     - price_1SYWIEGHcaLYld8I3aEP3Qpp
#     - price_1SYWIdGHcaLYld8IFWrZkAho
